#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
sys.path.append("/usr/share/sugar/extensions/webservice/harvest/")

import harvest.harvest

harvest = harvest.harvest.Harvest()
harvest.collect()#forced=True)
